// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLwwrG_Jl937F2B3ReXZT4GzoUV9GC8kE',
    appId: '1:675428563732:web:8a43774206ebf37476e001',
    messagingSenderId: '675428563732',
    projectId: 'shopiz-app-backend',
    authDomain: 'shopiz-app-backend.firebaseapp.com',
    storageBucket: 'shopiz-app-backend.firebasestorage.app',
    measurementId: 'G-4E5JL85GBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhcfYEdft5ysvRCcBX1go2cO6wgUuiaFc',
    appId: '1:675428563732:android:ef98713f61de11bf76e001',
    messagingSenderId: '675428563732',
    projectId: 'shopiz-app-backend',
    storageBucket: 'shopiz-app-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_BBXftDgCp3ZN3os3BxmG_-iXY8vXvqo',
    appId: '1:675428563732:ios:76edfe378d81fa5e76e001',
    messagingSenderId: '675428563732',
    projectId: 'shopiz-app-backend',
    storageBucket: 'shopiz-app-backend.firebasestorage.app',
    iosBundleId: 'com.example.shopiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_BBXftDgCp3ZN3os3BxmG_-iXY8vXvqo',
    appId: '1:675428563732:ios:76edfe378d81fa5e76e001',
    messagingSenderId: '675428563732',
    projectId: 'shopiz-app-backend',
    storageBucket: 'shopiz-app-backend.firebasestorage.app',
    iosBundleId: 'com.example.shopiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLwwrG_Jl937F2B3ReXZT4GzoUV9GC8kE',
    appId: '1:675428563732:web:5e770306b879b84c76e001',
    messagingSenderId: '675428563732',
    projectId: 'shopiz-app-backend',
    authDomain: 'shopiz-app-backend.firebaseapp.com',
    storageBucket: 'shopiz-app-backend.firebasestorage.app',
    measurementId: 'G-9KTP3FH2GH',
  );
}
